# Generated by Django 2.2.2 on 2020-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=122)),
                ('LastName', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('PhoneNumber', models.CharField(max_length=122)),
                ('Address', models.TextField()),
                ('Address2', models.TextField()),
                ('Country', models.CharField(max_length=122)),
                ('City', models.CharField(max_length=122)),
                ('State', models.CharField(max_length=122)),
                ('Zip', models.CharField(max_length=122)),
                ('PhotoID', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
