# Generated by Django 2.2.2 on 2020-08-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Address2',
        ),
    ]
