# Generated by Django 3.1.7 on 2021-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('sname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('shop_details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('sname', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('transport_details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
