# Generated by Django 3.1.7 on 2021-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shop_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Roha', max_length=122),
            preserve_default=False,
        ),
    ]
